baseurl = "/"
languageCode = "en-us"
title = "bloops"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[params]
description = "A simple, minimal blog for those who love text."
footer = "Open-Source | [Github](https://github.com/robotomize/bloopsbot) | [robotomize.me](https://robotomize.me)"
custom_css = ["css/theme-override.css"]

[markup.goldmark.renderer]
unsafe = true